# Configuration extracted from the prom/blackbox-exporter docker image
# Adapted configuration to prefer IPv4
# see https://www.robustperception.io/checking-for-http-200s-with-the-blackbox-exporter
# and https://github.com/prometheus/blackbox_exporter/blob/master/example.yml
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
