version: "3.7"
services:
  ubuntu-analysis-helper:
    build: ./ubuntu-analysis-helper
    image: ubuntu-analysis-helper
    container_name: ubuntu-analysis-helper

  sample-metrics-generator:
    build: ./sample-metrics-generator
    image: sample-metrics-generator
    container_name: sample-metrics-generator

  client1:
    build: ./client_golang_docker
    image: client-golang
    container_name: client1

  client2:
    build: ./client_golang_docker
    image: client-golang
    container_name: client2

  client3:
    build: ./client_golang_docker
    image: client-golang
    container_name: client3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
